/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fcmsf_final;

import javax.swing.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author asus
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public admin() {
        initComponents();
        setExtendedState(Home.MAXIMIZED_BOTH);
        yo.setVisible(true);
        yo.setSize(30,750);
        ho.setVisible(true);
        pa.setVisible(true);
        vo.setVisible(true);
        close.setContentAreaFilled(false);
        open.setContentAreaFilled(false);
        signin.setVisible(false);
        padd.setEnabled(false);
         pupd.setEnabled(false);
         cupd.setEnabled(false);
         cadd.setEnabled(false);
         vvol.setEnabled(false);
         vupd.setEnabled(false);
         pcadd.setEnabled(false);
         pcshow.setEnabled(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signin = new javax.swing.JPanel();
        use = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        sig = new javax.swing.JButton();
        lout = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        main = new javax.swing.JPanel();
        cupd = new javax.swing.JButton();
        vvol = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cadd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pupd = new javax.swing.JButton();
        vupd = new javax.swing.JButton();
        padd = new javax.swing.JButton();
        pcadd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        pcshow = new javax.swing.JButton();
        he = new javax.swing.JPanel();
        open = new javax.swing.JButton();
        sgn = new javax.swing.JLabel();
        sgn1 = new javax.swing.JButton();
        yo = new javax.swing.JPanel();
        ho = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        close = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        pa = new javax.swing.JButton();
        ch = new javax.swing.JButton();
        vo = new javax.swing.JButton();
        ad = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        signin.setBackground(new java.awt.Color(204, 204, 204));
        signin.setLayout(null);

        use.setBackground(new java.awt.Color(0, 0, 0));
        use.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        use.setText("USER");
        signin.add(use);
        use.setBounds(40, 90, 120, 30);

        password.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        password.setText("PASSWORD");
        signin.add(password);
        password.setBounds(40, 170, 120, 30);
        signin.add(user);
        user.setBounds(200, 90, 120, 30);

        sig.setText("SIGN IN");
        sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigActionPerformed(evt);
            }
        });
        signin.add(sig);
        sig.setBounds(150, 230, 72, 23);

        lout.setText("LOG OUT");
        lout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loutActionPerformed(evt);
            }
        });
        signin.add(lout);
        lout.setBounds(290, 230, 100, 23);
        signin.add(pass);
        pass.setBounds(200, 170, 120, 30);

        getContentPane().add(signin);
        signin.setBounds(520, 290, 520, 290);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setForeground(new java.awt.Color(255, 255, 255));
        main.setLayout(null);

        cupd.setBackground(new java.awt.Color(0, 153, 153));
        cupd.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        cupd.setText("<html>\nUPDATE<br>\n&ensp&ensp;&<br>\nDELETE\n\n</html>");
        cupd.setActionCommand("<html>UPDATE<br>\n<pre> &<br></pre>\nDELETE\n\n</html>");
        cupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupdActionPerformed(evt);
            }
        });
        main.add(cupd);
        cupd.setBounds(240, 240, 140, 80);

        vvol.setBackground(new java.awt.Color(0, 153, 153));
        vvol.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        vvol.setText("VOLUNTEER");
        vvol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vvolActionPerformed(evt);
            }
        });
        main.add(vvol);
        vvol.setBounds(1210, 150, 160, 33);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        main.add(jSeparator1);
        jSeparator1.setBounds(513, 50, 10, 750);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        main.add(jSeparator2);
        jSeparator2.setBounds(1026, 50, 10, 750);

        cadd.setBackground(new java.awt.Color(0, 153, 153));
        cadd.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        cadd.setText("ADD ");
        cadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caddActionPerformed(evt);
            }
        });
        main.add(cadd);
        cadd.setBounds(240, 150, 140, 30);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHILD");
        main.add(jLabel1);
        jLabel1.setBounds(130, 50, 380, 50);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PARENT");
        main.add(jLabel2);
        jLabel2.setBounds(510, 50, 513, 50);

        pupd.setBackground(new java.awt.Color(0, 153, 153));
        pupd.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        pupd.setText("<html>\nUPDATE<br>\n&ensp&ensp;&<br>\nDELETE\n\n</html>");
        pupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pupdActionPerformed(evt);
            }
        });
        main.add(pupd);
        pupd.setBounds(700, 240, 140, 80);

        vupd.setBackground(new java.awt.Color(0, 153, 153));
        vupd.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        vupd.setText("<html>\nUPDATE<br>\n&ensp&ensp;&<br>\nDELETE\n\n</html>");
        vupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vupdActionPerformed(evt);
            }
        });
        main.add(vupd);
        vupd.setBounds(1210, 230, 160, 80);

        padd.setBackground(new java.awt.Color(0, 153, 153));
        padd.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        padd.setText("ADD");
        padd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paddActionPerformed(evt);
            }
        });
        main.add(padd);
        padd.setBounds(700, 150, 140, 30);

        pcadd.setBackground(new java.awt.Color(0, 153, 153));
        pcadd.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        pcadd.setText("ADD");
        pcadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcaddActionPerformed(evt);
            }
        });
        main.add(pcadd);
        pcadd.setBounds(700, 600, 140, 33);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VOLUNTEER");
        main.add(jLabel3);
        jLabel3.setBounds(1030, 50, 510, 50);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setText("PARENT-CHILD");
        main.add(jLabel6);
        jLabel6.setBounds(690, 540, 170, 26);

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        main.add(jSeparator8);
        jSeparator8.setBounds(520, 500, 510, 20);

        pcshow.setBackground(new java.awt.Color(0, 153, 153));
        pcshow.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        pcshow.setText("SHOW");
        pcshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcshowActionPerformed(evt);
            }
        });
        main.add(pcshow);
        pcshow.setBounds(700, 670, 140, 33);

        he.setBackground(new java.awt.Color(255, 255, 255));
        he.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 204)));
        he.setLayout(null);

        open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-forward-button-30.png"))); // NOI18N
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        he.add(open);
        open.setBounds(10, 10, 30, 30);

        sgn.setBackground(new java.awt.Color(255, 255, 153));
        sgn.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        sgn.setText("<html> <pre>                                                  X FOSTER CARE");
        he.add(sgn);
        sgn.setBounds(0, 0, 1540, 50);

        sgn1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        sgn1.setText("SIGN IN");
        sgn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgn1ActionPerformed(evt);
            }
        });
        he.add(sgn1);
        sgn1.setBounds(1410, 10, 90, 25);

        main.add(he);
        he.setBounds(0, 0, 1540, 50);

        yo.setBackground(new java.awt.Color(255, 255, 255));
        yo.setForeground(new java.awt.Color(255, 255, 255));
        yo.setLayout(null);

        ho.setBackground(new java.awt.Color(0, 0, 0));
        ho.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ho.setForeground(new java.awt.Color(0, 204, 204));
        ho.setText("HOME");
        ho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoActionPerformed(evt);
            }
        });
        yo.add(ho);
        ho.setBounds(30, 70, 100, 30);

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator11);
        jSeparator11.setBounds(0, 110, 130, 10);

        jSeparator12.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator12);
        jSeparator12.setBounds(0, 170, 130, 10);

        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-go-back-30.png"))); // NOI18N
        close.setBorder(null);
        close.setOpaque(true);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        yo.add(close);
        close.setBounds(90, 10, 30, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-home-page-30.png"))); // NOI18N
        yo.add(jLabel4);
        jLabel4.setBounds(0, 70, 30, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-family-30.png"))); // NOI18N
        yo.add(jLabel9);
        jLabel9.setBounds(0, 130, 30, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-organization-chart-people-30.png"))); // NOI18N
        yo.add(jLabel10);
        jLabel10.setBounds(0, 310, 30, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-administrator-male-30.png"))); // NOI18N
        yo.add(jLabel11);
        jLabel11.setBounds(0, 370, 30, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-school-girl-30.png"))); // NOI18N
        yo.add(jLabel7);
        jLabel7.setBounds(0, 190, 30, 30);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator3);
        jSeparator3.setBounds(0, 230, 130, 10);

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator4);
        jSeparator4.setBounds(0, 50, 130, 10);

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator5);
        jSeparator5.setBounds(0, 290, 130, 10);

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator6);
        jSeparator6.setBounds(0, 350, 130, 10);

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator7);
        jSeparator7.setBounds(0, 410, 130, 10);

        pa.setBackground(new java.awt.Color(0, 0, 0));
        pa.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        pa.setForeground(new java.awt.Color(0, 204, 204));
        pa.setText("PARENT");
        pa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paActionPerformed(evt);
            }
        });
        yo.add(pa);
        pa.setBounds(30, 130, 100, 30);

        ch.setBackground(new java.awt.Color(0, 0, 0));
        ch.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ch.setForeground(new java.awt.Color(0, 204, 204));
        ch.setText("CHILD");
        ch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chActionPerformed(evt);
            }
        });
        yo.add(ch);
        ch.setBounds(30, 190, 100, 30);

        vo.setBackground(new java.awt.Color(0, 0, 0));
        vo.setForeground(new java.awt.Color(0, 204, 204));
        vo.setText("VOLUNTEER");
        vo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voActionPerformed(evt);
            }
        });
        yo.add(vo);
        vo.setBounds(30, 250, 100, 30);

        ad.setBackground(new java.awt.Color(0, 0, 0));
        ad.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ad.setForeground(new java.awt.Color(0, 204, 204));
        ad.setText("ADMIN");
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });
        yo.add(ad);
        ad.setBounds(30, 370, 100, 30);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 204));
        jButton5.setText("ABOUT US");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        yo.add(jButton5);
        jButton5.setBounds(30, 310, 100, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-volunteer-30.jpeg.png"))); // NOI18N
        yo.add(jLabel8);
        jLabel8.setBounds(0, 250, 30, 30);

        main.add(yo);
        yo.setBounds(0, 50, 130, 750);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/admin.jpg"))); // NOI18N
        main.add(background);
        background.setBounds(0, 0, 1540, 800);

        getContentPane().add(main);
        main.setBounds(0, 0, 1600, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vvolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vvolActionPerformed
        Vtable vt=new Vtable();
        vt.show();
        dispose();
       
    }//GEN-LAST:event_vvolActionPerformed

    private void caddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddActionPerformed
        a_child ac=new a_child();
        ac.show();
        dispose();
    }//GEN-LAST:event_caddActionPerformed

    private void paddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paddActionPerformed
                     
        a_par ap=new a_par();
        ap.show();
        dispose();
    }//GEN-LAST:event_paddActionPerformed

    private void cupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupdActionPerformed
        u_child uc=new u_child();
        uc.show();
        dispose();
    }//GEN-LAST:event_cupdActionPerformed

    private void vupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vupdActionPerformed
       u_vol uv=new u_vol();
       uv.show();
       dispose();
    }//GEN-LAST:event_vupdActionPerformed

    private void pcaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcaddActionPerformed
        parchild pa=new parchild();
        pa.show();
        dispose();
    }//GEN-LAST:event_pcaddActionPerformed

    private void pcshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcshowActionPerformed
       s_parchild sp=new s_parchild();
       sp.show();
       dispose();
    }//GEN-LAST:event_pcshowActionPerformed

    private void pupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pupdActionPerformed
        u_parent up=new u_parent();
        up.show();
        dispose();
    }//GEN-LAST:event_pupdActionPerformed

    private void sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigActionPerformed
               String username=user.getText();
               String password=pass.getText();
               if(username.equals("Aiman") && password.equals("aiman")) {
                signin.setVisible(false);
        padd.setEnabled(true);
         pupd.setEnabled(true);
         cupd.setEnabled(true);
         cadd.setEnabled(true);
         vvol.setEnabled(true);
         vupd.setEnabled(true);
         pcadd.setEnabled(true);
         pcshow.setEnabled(true);
       
         user.setText("");
         pass.setText("");
         
         
               }
               else
               {
                    JOptionPane.showMessageDialog(null, "INVALID USERNAME OR PASSWORD");
               }
         
    }//GEN-LAST:event_sigActionPerformed

    private void loutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loutActionPerformed
        signin.setVisible(false);
        padd.setEnabled(false);
         pupd.setEnabled(false);
         cupd.setEnabled(false);
         cadd.setEnabled(false);
         vvol.setEnabled(false);
         vupd.setEnabled(false);
         pcadd.setEnabled(false);
         pcshow.setEnabled(false);
      
    }//GEN-LAST:event_loutActionPerformed

    private void hoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoActionPerformed
        Home ho=new Home();//to open Home page
        ho.show();
        dispose();
    }//GEN-LAST:event_hoActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        yo.setVisible(true);              //to close yo sidepanel
        yo.setSize(30,750);
        ho.setVisible(true);
        ch.setVisible(true);
        vo.setVisible(true);
    }//GEN-LAST:event_closeActionPerformed

    private void paActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paActionPerformed
        Parent pa =new Parent();        //to open parent
        pa.show();
        dispose();
    }//GEN-LAST:event_paActionPerformed

    private void chActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chActionPerformed
        child ch =new child();        //to open parent
        ch.show();
        dispose();
    }//GEN-LAST:event_chActionPerformed

    private void voActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voActionPerformed
        Volunteer vo=new Volunteer();        //To open Volunteer
        vo.show();
        dispose();
    }//GEN-LAST:event_voActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        admin ad=new admin();
        ad.show();
        dispose();
    }//GEN-LAST:event_adActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        org og=new org();
        og.show();
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        yo.setVisible(true);               //to open yo side panel
        yo.setSize(130,750);
        ho.setVisible(true);
        ch.setVisible(true);
        vo.setVisible(true);
        //he.setVisible(false);
    }//GEN-LAST:event_openActionPerformed

    private void sgn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgn1ActionPerformed
       signin.setVisible(true);
    }//GEN-LAST:event_sgn1ActionPerformed
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }
    private javax.swing.JTable jTable1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ad;
    private javax.swing.JLabel background;
    private javax.swing.JButton cadd;
    private javax.swing.JButton ch;
    private javax.swing.JButton close;
    private javax.swing.JButton cupd;
    private javax.swing.JPanel he;
    private javax.swing.JButton ho;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JButton lout;
    private javax.swing.JPanel main;
    private javax.swing.JButton open;
    private javax.swing.JButton pa;
    private javax.swing.JButton padd;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel password;
    private javax.swing.JButton pcadd;
    private javax.swing.JButton pcshow;
    private javax.swing.JButton pupd;
    private javax.swing.JLabel sgn;
    private javax.swing.JButton sgn1;
    private javax.swing.JButton sig;
    private javax.swing.JPanel signin;
    private javax.swing.JLabel use;
    private javax.swing.JTextField user;
    private javax.swing.JButton vo;
    private javax.swing.JButton vupd;
    private javax.swing.JButton vvol;
    private javax.swing.JPanel yo;
    // End of variables declaration//GEN-END:variables
}
