/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fcmsf_final;
import fcmsf_final.admin;
import java.sql.Connection;
import java.sql.Statement;
import java.awt.event.KeyEvent;
import java.sql.*;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author asus
 */
public class u_parent extends javax.swing.JFrame {

    /**
     * Creates new form u_parent
     */
    public u_parent() {
        initComponents();
         setExtendedState(Home.MAXIMIZED_BOTH);
        yo.setVisible(true);
        yo.setSize(30,750);
        ho.setVisible(true);
        pa.setVisible(true);
        vo.setVisible(true);
        close.setContentAreaFilled(false);
        open.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        pid = new javax.swing.JLabel();
        pidt = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        namet = new javax.swing.JTextField();
        gen = new javax.swing.JLabel();
        genc = new javax.swing.JComboBox<>();
        rel = new javax.swing.JLabel();
        relc = new javax.swing.JComboBox<>();
        phone = new javax.swing.JLabel();
        phnc = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        agt = new javax.swing.JTextField();
        oid = new javax.swing.JLabel();
        yo = new javax.swing.JPanel();
        ho = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        close = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        pa = new javax.swing.JButton();
        ch = new javax.swing.JButton();
        vo = new javax.swing.JButton();
        ad = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        oidc = new javax.swing.JComboBox<>();
        subm = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        search = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        he = new javax.swing.JPanel();
        open = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(null);

        pid.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        pid.setText("PID");
        main.add(pid);
        pid.setBounds(580, 60, 70, 26);
        main.add(pidt);
        pidt.setBounds(650, 60, 120, 30);

        name.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        name.setText("NAME");
        main.add(name);
        name.setBounds(440, 180, 70, 30);
        main.add(namet);
        namet.setBounds(570, 180, 120, 30);

        gen.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        gen.setText("GENDER");
        main.add(gen);
        gen.setBounds(840, 180, 90, 30);

        genc.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        genc.setMaximumRowCount(4);
        genc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER" }));
        main.add(genc);
        genc.setBounds(1020, 180, 120, 30);

        rel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        rel.setText("RELIGION");
        main.add(rel);
        rel.setBounds(850, 300, 100, 30);

        relc.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        relc.setMaximumRowCount(5);
        relc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HINDU", "MUSLIM", "CHRISTIAN", "OTHER", " " }));
        main.add(relc);
        relc.setBounds(1020, 300, 120, 30);

        phone.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        phone.setText("PHONE");
        main.add(phone);
        phone.setBounds(430, 440, 80, 26);

        phnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phncActionPerformed(evt);
            }
        });
        main.add(phnc);
        phnc.setBounds(570, 430, 120, 30);

        age.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        age.setText("AGE");
        main.add(age);
        age.setBounds(450, 300, 50, 26);
        main.add(agt);
        agt.setBounds(570, 300, 120, 30);

        oid.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        oid.setText("OID");
        main.add(oid);
        oid.setBounds(860, 430, 70, 26);

        yo.setBackground(new java.awt.Color(255, 255, 255));
        yo.setForeground(new java.awt.Color(255, 255, 255));
        yo.setLayout(null);

        ho.setBackground(new java.awt.Color(0, 0, 0));
        ho.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ho.setForeground(new java.awt.Color(0, 204, 204));
        ho.setText("HOME");
        ho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoActionPerformed(evt);
            }
        });
        yo.add(ho);
        ho.setBounds(30, 70, 100, 30);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator1);
        jSeparator1.setBounds(0, 110, 130, 10);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator2);
        jSeparator2.setBounds(0, 170, 130, 10);

        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-go-back-30.png"))); // NOI18N
        close.setBorder(null);
        close.setOpaque(true);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        yo.add(close);
        close.setBounds(90, 10, 30, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-home-page-30.png"))); // NOI18N
        yo.add(jLabel4);
        jLabel4.setBounds(0, 70, 30, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-family-30.png"))); // NOI18N
        yo.add(jLabel9);
        jLabel9.setBounds(0, 130, 30, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-organization-chart-people-30.png"))); // NOI18N
        yo.add(jLabel10);
        jLabel10.setBounds(0, 310, 30, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-administrator-male-30.png"))); // NOI18N
        yo.add(jLabel11);
        jLabel11.setBounds(0, 370, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-school-girl-30.png"))); // NOI18N
        yo.add(jLabel2);
        jLabel2.setBounds(0, 190, 30, 30);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator3);
        jSeparator3.setBounds(0, 230, 130, 10);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator4);
        jSeparator4.setBounds(0, 50, 130, 10);

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator8);
        jSeparator8.setBounds(0, 290, 130, 10);

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator9);
        jSeparator9.setBounds(0, 350, 130, 10);

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator10);
        jSeparator10.setBounds(0, 410, 130, 10);

        pa.setBackground(new java.awt.Color(0, 0, 0));
        pa.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        pa.setForeground(new java.awt.Color(0, 204, 204));
        pa.setText("PARENT");
        pa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paActionPerformed(evt);
            }
        });
        yo.add(pa);
        pa.setBounds(30, 130, 100, 30);

        ch.setBackground(new java.awt.Color(0, 0, 0));
        ch.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ch.setForeground(new java.awt.Color(0, 204, 204));
        ch.setText("CHILD");
        ch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chActionPerformed(evt);
            }
        });
        yo.add(ch);
        ch.setBounds(30, 190, 100, 30);

        vo.setBackground(new java.awt.Color(0, 0, 0));
        vo.setForeground(new java.awt.Color(0, 204, 204));
        vo.setText("VOLUNTEER");
        vo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voActionPerformed(evt);
            }
        });
        yo.add(vo);
        vo.setBounds(30, 250, 100, 30);

        ad.setBackground(new java.awt.Color(0, 0, 0));
        ad.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ad.setForeground(new java.awt.Color(0, 204, 204));
        ad.setText("ADMIN");
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });
        yo.add(ad);
        ad.setBounds(30, 370, 100, 30);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 204));
        jButton5.setText("ABOUT US");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        yo.add(jButton5);
        jButton5.setBounds(30, 310, 100, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-volunteer-30.jpeg.png"))); // NOI18N
        yo.add(jLabel8);
        jLabel8.setBounds(0, 250, 30, 30);

        main.add(yo);
        yo.setBounds(0, 50, 130, 750);

        oidc.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        oidc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        oidc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oidcActionPerformed(evt);
            }
        });
        main.add(oidc);
        oidc.setBounds(1020, 430, 120, 30);

        subm.setBackground(new java.awt.Color(0, 0, 0));
        subm.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        subm.setForeground(new java.awt.Color(0, 204, 204));
        subm.setText("UPDATE");
        subm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submActionPerformed(evt);
            }
        });
        main.add(subm);
        subm.setBounds(560, 570, 160, 40);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        main.add(jSeparator5);
        jSeparator5.setBounds(0, 503, 1540, 20);

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        main.add(jSeparator6);
        jSeparator6.setBounds(0, 100, 1540, 10);

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        main.add(jSeparator7);
        jSeparator7.setBounds(770, 101, 10, 404);

        search.setBackground(new java.awt.Color(0, 0, 0));
        search.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(0, 204, 204));
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        main.add(search);
        search.setBounds(810, 60, 100, 28);

        reset.setBackground(new java.awt.Color(0, 0, 0));
        reset.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 204, 204));
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        main.add(reset);
        reset.setBounds(710, 720, 120, 40);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 204));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        main.add(jButton3);
        jButton3.setBounds(820, 570, 160, 40);

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        main.add(jSeparator11);
        jSeparator11.setBounds(0, 670, 1540, 20);

        he.setBackground(new java.awt.Color(255, 255, 255));
        he.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 204)));
        he.setLayout(null);

        open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-forward-button-30.png"))); // NOI18N
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        he.add(open);
        open.setBounds(10, 10, 30, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 153));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel7.setText("<html>\n<pre>                                                  X FOSTER CARE");
        he.add(jLabel7);
        jLabel7.setBounds(0, 0, 1540, 50);

        main.add(he);
        he.setBounds(0, 0, 1540, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/par.jpg"))); // NOI18N
        main.add(background);
        background.setBounds(0, 50, 1540, 750);

        getContentPane().add(main);
        main.setBounds(0, 0, 1540, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phncActionPerformed

    private void oidcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oidcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oidcActionPerformed

    private void submActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submActionPerformed
        String PID=pidt.getText();
        String NAME=namet.getText();
        String AGE=agt.getText();
        String RELIGION=(String)relc.getSelectedItem();
        String GENDER=(String)genc.getSelectedItem();
        String PHONE=phnc.getText();      
        String OID=(String)oidc.getSelectedItem();
        try{
            Connection con=FCMSF_FINAL .getCon();
            Statement st=con.createStatement();
            st.executeUpdate("update parent set NAME='"+NAME+"',AGE='"+AGE+"',PHONE='"+PHONE+"',GENDER='"+GENDER+"',RELIGION='"+RELIGION+"',OID='"+OID+"'where PID='"+PID+"' ");
            JOptionPane.showMessageDialog(null, "SUCESSFULLY UPDATED");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_submActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String PID=pidt.getText();       
        try{  Connection con=FCMSF_FINAL .getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from PARENT where PID='"+PID+"'");
            if(rs.next())
            {
                namet.setText(rs.getString(2));
                genc.setSelectedItem(rs.getString(4));
                relc.setSelectedItem(rs.getString(5));
                phnc.setText(rs.getString(6));
                agt.setText(rs.getString(3));              
                oidc.setSelectedItem(rs.getString(7));
                pidt.setEditable(false);
            }
            else
            JOptionPane.showMessageDialog(null,"PID does not exist");
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_searchActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        setVisible(false);
        new u_parent().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      String PID=pidt.getText();
        try{
            Connection con=FCMSF_FINAL .getCon();
            Statement st=con.createStatement();
            st.executeUpdate("DELETE FROM PARENT where PID='"+PID+"'");
            JOptionPane.showMessageDialog(null, "SUCESSFULLY DELETED");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        yo.setVisible(true);               //to open yo side panel
        yo.setSize(130,750);
        ho.setVisible(true);
        ch.setVisible(true);
        vo.setVisible(true);
        //he.setVisible(false);
    }//GEN-LAST:event_openActionPerformed

    private void hoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoActionPerformed
        Home ho=new Home();//to open Home page
        ho.show();
        dispose();
    }//GEN-LAST:event_hoActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        yo.setVisible(true);              //to close yo sidepanel
        yo.setSize(30,750);
        ho.setVisible(true);
        ch.setVisible(true);
        vo.setVisible(true);
    }//GEN-LAST:event_closeActionPerformed

    private void paActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paActionPerformed
        Parent pa =new Parent();        //to open parent
        pa.show();
        dispose();
    }//GEN-LAST:event_paActionPerformed

    private void chActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chActionPerformed
        child ch =new child();        //to open parent
        ch.show();
        dispose();
    }//GEN-LAST:event_chActionPerformed

    private void voActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voActionPerformed
        Volunteer vo=new Volunteer();        //To open Volunteer
        vo.show();
        dispose();
    }//GEN-LAST:event_voActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        admin ad=new admin();
        ad.show();
        dispose();
    }//GEN-LAST:event_adActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        org og=new org();
        og.show();
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(u_parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(u_parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(u_parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(u_parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new u_parent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ad;
    private javax.swing.JLabel age;
    private javax.swing.JTextField agt;
    private javax.swing.JLabel background;
    private javax.swing.JButton ch;
    private javax.swing.JButton close;
    private javax.swing.JLabel gen;
    private javax.swing.JComboBox<String> genc;
    private javax.swing.JPanel he;
    private javax.swing.JButton ho;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel main;
    private javax.swing.JLabel name;
    private javax.swing.JTextField namet;
    private javax.swing.JLabel oid;
    private javax.swing.JComboBox<String> oidc;
    private javax.swing.JButton open;
    private javax.swing.JButton pa;
    private javax.swing.JTextField phnc;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel pid;
    private javax.swing.JTextField pidt;
    private javax.swing.JLabel rel;
    private javax.swing.JComboBox<String> relc;
    private javax.swing.JButton reset;
    private javax.swing.JButton search;
    private javax.swing.JButton subm;
    private javax.swing.JButton vo;
    private javax.swing.JPanel yo;
    // End of variables declaration//GEN-END:variables
}
