/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fcmsf_final;

import fcmsf_final.Parent;
import fcmsf_final.Home;

/**
 *
 * @author asus
 */
public class Volunteer extends javax.swing.JFrame {

    /**
     * Creates new form Volunteer
     */
    public Volunteer() {
        initComponents();
        setExtendedState(Home.MAXIMIZED_BOTH);
        yo.setVisible(true);
        yo.setSize(30,750);
        ho.setVisible(true);
        pa.setVisible(true);
        vo.setVisible(true);
        close.setContentAreaFilled(false);
        open.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Vmain = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        yo = new javax.swing.JPanel();
        ho = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        close = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        pa = new javax.swing.JButton();
        ch = new javax.swing.JButton();
        vo = new javax.swing.JButton();
        ad = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        he = new javax.swing.JPanel();
        open1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        open = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Vmain.setBackground(new java.awt.Color(255, 255, 255));
        Vmain.setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Register As Volunteer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Vmain.add(jButton1);
        jButton1.setBounds(580, 400, 380, 70);

        yo.setBackground(new java.awt.Color(255, 255, 255));
        yo.setForeground(new java.awt.Color(255, 255, 255));
        yo.setLayout(null);

        ho.setBackground(new java.awt.Color(0, 0, 0));
        ho.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ho.setForeground(new java.awt.Color(0, 204, 204));
        ho.setText("HOME");
        ho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoActionPerformed(evt);
            }
        });
        yo.add(ho);
        ho.setBounds(30, 70, 100, 30);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator1);
        jSeparator1.setBounds(0, 110, 130, 10);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator2);
        jSeparator2.setBounds(0, 170, 130, 10);

        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-go-back-30.png"))); // NOI18N
        close.setBorder(null);
        close.setOpaque(true);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        yo.add(close);
        close.setBounds(90, 10, 30, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-home-page-30.png"))); // NOI18N
        yo.add(jLabel4);
        jLabel4.setBounds(0, 70, 30, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-family-30.png"))); // NOI18N
        yo.add(jLabel9);
        jLabel9.setBounds(0, 130, 30, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-organization-chart-people-30.png"))); // NOI18N
        yo.add(jLabel10);
        jLabel10.setBounds(0, 310, 30, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-administrator-male-30.png"))); // NOI18N
        yo.add(jLabel11);
        jLabel11.setBounds(0, 370, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-school-girl-30.png"))); // NOI18N
        yo.add(jLabel2);
        jLabel2.setBounds(0, 190, 30, 30);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator3);
        jSeparator3.setBounds(0, 230, 130, 10);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator4);
        jSeparator4.setBounds(0, 50, 130, 10);

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator5);
        jSeparator5.setBounds(0, 290, 130, 10);

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator6);
        jSeparator6.setBounds(0, 350, 130, 10);

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        yo.add(jSeparator7);
        jSeparator7.setBounds(0, 410, 130, 10);

        pa.setBackground(new java.awt.Color(0, 0, 0));
        pa.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        pa.setForeground(new java.awt.Color(0, 204, 204));
        pa.setText("PARENT");
        pa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paActionPerformed(evt);
            }
        });
        yo.add(pa);
        pa.setBounds(30, 130, 100, 30);

        ch.setBackground(new java.awt.Color(0, 0, 0));
        ch.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ch.setForeground(new java.awt.Color(0, 204, 204));
        ch.setText("CHILD");
        ch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chActionPerformed(evt);
            }
        });
        yo.add(ch);
        ch.setBounds(30, 190, 100, 30);

        vo.setBackground(new java.awt.Color(0, 0, 0));
        vo.setForeground(new java.awt.Color(0, 204, 204));
        vo.setText("VOLUNTEER");
        vo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voActionPerformed(evt);
            }
        });
        yo.add(vo);
        vo.setBounds(30, 250, 100, 30);

        ad.setBackground(new java.awt.Color(0, 0, 0));
        ad.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ad.setForeground(new java.awt.Color(0, 204, 204));
        ad.setText("ADMIN");
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });
        yo.add(ad);
        ad.setBounds(30, 370, 100, 30);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 204));
        jButton5.setText("ABOUT US");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        yo.add(jButton5);
        jButton5.setBounds(30, 310, 100, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-volunteer-30.jpeg.png"))); // NOI18N
        yo.add(jLabel8);
        jLabel8.setBounds(0, 250, 30, 30);

        Vmain.add(yo);
        yo.setBounds(0, 50, 130, 750);

        he.setBackground(new java.awt.Color(255, 255, 255));
        he.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 204)));
        he.setLayout(null);

        open1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-forward-button-30.png"))); // NOI18N
        open1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open1ActionPerformed(evt);
            }
        });
        he.add(open1);
        open1.setBounds(10, 10, 30, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 153));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel7.setText("<html>\n<pre>                                                  X FOSTER CARE");
        he.add(jLabel7);
        jLabel7.setBounds(0, 0, 1540, 50);

        open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-forward-button-30.png"))); // NOI18N
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        he.add(open);
        open.setBounds(10, 10, 30, 30);

        Vmain.add(he);
        he.setBounds(0, 0, 1540, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/vol1.jpg"))); // NOI18N
        Vmain.add(background);
        background.setBounds(0, 50, 1540, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Vmain, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Vmain, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Vregister vr=new Vregister();
        vr.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        yo.setVisible(true);               //to open yo side panel
        yo.setSize(130,750);
        ho.setVisible(true);
        ch.setVisible(true);
        vo.setVisible(true);
        //he.setVisible(false);
    }//GEN-LAST:event_openActionPerformed

    private void hoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoActionPerformed
        Home ho=new Home();//to open Home page
        ho.show();
        dispose();
    }//GEN-LAST:event_hoActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        yo.setVisible(true);              //to close yo sidepanel
        yo.setSize(30,750);
        ho.setVisible(true);
        ch.setVisible(true);
        vo.setVisible(true);
    }//GEN-LAST:event_closeActionPerformed

    private void paActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paActionPerformed
        Parent pa =new Parent();        //to open parent
        pa.show();
        dispose();
    }//GEN-LAST:event_paActionPerformed

    private void chActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chActionPerformed
        child ch =new child();        //to open parent
        ch.show();
        dispose();
    }//GEN-LAST:event_chActionPerformed

    private void voActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voActionPerformed
        Volunteer vo=new Volunteer();        //To open Volunteer
        vo.show();
        dispose();
    }//GEN-LAST:event_voActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        admin ad=new admin();
        ad.show();
        dispose();
    }//GEN-LAST:event_adActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        org og=new org();
        og.show();
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void open1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open1ActionPerformed
        yo.setVisible(true);               //to open yo side panel
        yo.setSize(130,750);
        ho.setVisible(true);
        ch.setVisible(true);
        vo.setVisible(true);
        //he.setVisible(false);
    }//GEN-LAST:event_open1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volunteer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Volunteer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Vmain;
    private javax.swing.JButton ad;
    private javax.swing.JLabel background;
    private javax.swing.JButton ch;
    private javax.swing.JButton close;
    private javax.swing.JPanel he;
    private javax.swing.JButton ho;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton open;
    private javax.swing.JButton open1;
    private javax.swing.JButton pa;
    private javax.swing.JButton vo;
    private javax.swing.JPanel yo;
    // End of variables declaration//GEN-END:variables
}
